// src/questions.js
export const questionBank = [
  { id: 1, type: 'choice', q: "我第一次找你说话是什么话题？", options: ["尬聊", "英语题", "问教室", "高数题"], a: "高数题" },
  { id: 2, type: 'choice', q: "请在以下食物中找出我唯一喜欢吃的", options: ["菠菜", "香菇", "蘑菇", "黄花菜", "苦瓜", "手握寿司", "切的很碎的生姜", "猫山王榴莲"], a: "手握寿司" },
  { id: 3, type: 'choice', q: "我们第一次看的电影是？", options: ["唐人街探案3", "飞驰人生2", "不速来客", "深海", "封神榜"], a: "不速来客" },
  { id: 4, type: 'choice', q: "我最喜欢你送我的哪个礼物？", options: ["耀西系列", "绿色的单肩包", "遛狗绳拼豆", "100颗星星折纸", "乐高玫瑰花", "零食花"], a: "100颗星星折纸" },
  { id: 5, type: 'choice', q: "我的MBTI？", options: ["INTP", "INFP", "ISFJ", "ISTP"], a: "INFP" },
  { id: 6, type: 'input', q: "我最喜欢叫你的外号？", a: "麻麻狗" },
  { id: 7, type: 'choice', q: "我们的关系是？", options: ["男女朋友", "麻麻与哈狗", "老夫老妻"], a: "麻麻与哈狗" },
  { id: 8, type: 'choice', q: "我的真实身高？", options: ["163cm", "164cm", "165cm", "166cm", "167cm"], a: "165cm" },
  { id: 9, type: 'choice', q: "下面哪个化妆品我不用？", options: ["散粉", "唇釉", "卧蚕", "修容", "高光"], a: "修容" },
  { id: 10, type: 'choice', q: "下面哪个电视剧我没看过？", options: ["花千骨", "三生三世十里桃花", "我好像遇到了救星", "沉香如屑 沉香重华"], a: "三生三世十里桃花" },
  { id: 11, type: 'choice', q: "我最喜欢哪种电视剧？", options: ["BE(Bad Ending)", "HE(Happy Ending)", "OE(Open Ending)"], a: "BE(Bad Ending)" },
  { id: 12, type: 'choice', q: "下面哪个编程语言我不会写？", options: ["Python", "Java", "Visual Basic", "JavaScript"], a: "JavaScript" },
  { id: 13, type: 'choice', q: "我最喜欢的颜色？", options: ["绿色", "黄色", "紫色"], a: "绿色" },
  { id: 14, type: 'input', q: "我们在一起的日期(YYYYMMDD格式)", a: "20211006" },
  { id: 15, type: 'choice', q: "我最大的优点？", options: ["漂亮", "人品好", "学习好", "全都是"], a: "全都是" },
  { id: 16, type: 'choice', q: "我最希望自己改进的地方？", options: ["外貌身材方面", "容易哭", "不和人社交", "潜在自卑"], a: "潜在自卑" },
  { id: 17, type: 'choice', q: "我最不满意自己的哪个身体部位？", options: ["腿腿", "嘴嘴", "胸胸", "屁屁", "腰腰"], a: "腰腰" },
  { id: 18, type: 'choice', q: "我的墩儿有几个驼峰？", options: ["一个", "两个"], a: "两个" },
  { id: 19, type: 'choice', q: "以我开始喜欢的时间的顺序排序", options: ["王一博 陈赫 成毅 “老大”", "成毅 王一博 陈赫 “老大”", "陈赫 王一博 “老大” 成毅", "陈赫 王一博 成毅 “老大”"], a: "陈赫 王一博 成毅 “老大”" },
  { id: 20, type: 'choice', q: "针对此次的生日礼物新形式，你的反应是", options: ["哇我的宝宝好厉害！！好有新意！！我要珍藏这个网页一辈子！！", "都行，我都行", "写个网页又没花钱，不是很喜欢"], a: "哇我的宝宝好厉害！！好有新意！！我要珍藏这个网页一辈子！！" },
  { id: 21, type: 'choice', q: "下面明星中，我有点反感的是", options: ["Angelababy杨颖", "王祖蓝", "王宝强", "郑恺"], a: "王祖蓝" },
  { id: 22, type: 'choice', q: "你错了没！", options: ["错了", "没错"], a: "错了" },
  { id: 23, type: 'input', q: "你每次出门前要说什么话？", a: "麻麻也爱你哦" },
  { id: 24, type: 'choice', q: "很冷和很热我宁愿选哪个？", options: ["很冷", "很热"], a: "很冷" },
  { id: 25, type: 'choice', q: "大一的时候我送你一只大虫子，它叫什么", options: ["桔子", "雪球", "饺子", "吉吉"], a: "饺子" },
  { id: 26, type: 'choice', q: "我一般来例假是提前还是推迟？", options: ["提前", "准时", "推迟"], a: "推迟" },
  { id: 27, type: 'choice', q: "下面哪个因素导致我最不想出门？", options: ["没洗头", "长痘痘", "没有搭配好的衣服", "胳膊毛没刮或者腿腿起皮"], a: "长痘痘" },
  { id: 28, type: 'choice', q: "我干嘛要设置这么多题目啊，我想不出来了啊啊啊，你选第一个吧", options: ["第一个", "第二个"], a: "第二个" },
  { id: 29, type: 'choice', q: "我干嘛要设置这么多题目啊，我想不出来了啊啊啊，你选第二个吧", options: ["第一个", "第二个"], a: "第一个" },
  { id: 30, type: 'choice', q: "哈狗爱你呦", options: ["麻麻也爱你哦", "麻麻也爱你呦", "麻麻也爱你哩"], a: "麻麻也爱你呦" },
];